version: 2.1

commands:
  setup_solc:
    steps:
      - run:
          name: Setup native solc
          command: sudo cp ~/project/.circleci/solc /bin

jobs:
  build-and-test:
    docker:
      - image: circleci/node:11.15
    steps:
      - checkout
      - setup_solc
      - run: npm install
      - run: npm run lint
      - run: npm run build
      - run: npm test
      - run: npm run coverage
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  build-and-test:
    jobs:
      - build-and-test
